url: "https://vikaslazarus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Touristhill.in" # the name of your site, e.g. ACME Corp.
tel: "+918219471645"