url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://vikaslazarus.github.io/" # the subpath of your site, e.g. /blog
title: "Touristhill.in" # the name of your site, e.g. ACME Corp.
